apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-vars
data:
  DB_NAME: {{ .Values.backend.config.dbName | quote }}
  DB_USER: {{ .Values.backend.config.dbUser | quote }}
  DB_HOST: {{ .Values.backend.config.dbHost | quote }}
  DB_PORT: {{ .Values.backend.config.dbPort | quote }}
