apiVersion: v1
kind: Service
metadata:
  name: chatapp-backend
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - name: backend-port
      port: {{ .Values.backend.service.port }}
      targetPort: backend-port
