apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deploy-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-admin
  namespace: default
roleRef:
  kind: Role
  name: pod-deploy-role
  apiGroup: rbac.authorization.k8s.io

