apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chatapp-cluster
  region: ap-south-1

vpc:
  id: vpc-0d7a6a31be7babf08
  subnets:
    public:
      ap-south-1a:
        id: subnet-006ad0184731809d8
      ap-south-1b:
        id: subnet-0085385f2540175ff
    private:
      ap-south-1a:
        id: subnet-0ac5c6471f4ad6783
      ap-south-1b:
        id: subnet-06faaf4fa7328a192

iam:
  withOIDC: true

managedNodeGroups:
  - name: chatapp-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 40
    privateNetworking: true
    labels:
      app: chatapp
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

