apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.sec.rootPass }}
  MYSQL_PASSWORD: {{ .Values.database.sec.userPass }}
