apiVersion: v1
kind: Service
metadata: 
  name:  mysql-headless
spec:
  clusterIP: None
  selector:
    app:  {{ .Release.Name }}-chatapp-db
  ports:
    - name: mysql-port
      port: 3306
      targetPort: db-port
