---
apiVersion: v1
kind: Pod
metadata:
  name: chatapp-db-pod
  labels:
    app: database
spec:
  containers:
    - name: chatapp-mysql
      image: mysql
      ports:
        - name: db-port
          containerPort: 3306
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 15
        periodSeconds: 5
        failureThreshold: 3
      startupProbe:
        tcpSocket:
          port: 3306
        periodSeconds: 5
        failureThreshold: 3
      envFrom:
        - configMapRef:
            name: db-vars
        - secretRef:
            name: db-secrets

